# Generated by Django 3.0.14 on 2021-05-18 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='House', max_length=20, verbose_name='ハウス名')),
                ('common_fee', models.PositiveIntegerField(blank=True, default=500, null=True, verbose_name='共益費')),
                ('common_fee_date', models.PositiveIntegerField(blank=True, default=25, null=True, verbose_name='共益費の支払い期日')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='作成日')),
            ],
        ),
        migrations.CreateModel(
            name='RequestHouseOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='日付')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.House')),
            ],
        ),
        migrations.CreateModel(
            name='RequestChHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('request_house', models.CharField(blank=True, max_length=256, null=True, verbose_name='希望するハウス')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='日付')),
                ('current_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.House')),
            ],
        ),
        migrations.CreateModel(
            name='Inquire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('content', models.CharField(blank=True, max_length=256, null=True, verbose_name='問い合わせ内容')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='日付')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('name', models.CharField(default='ユーザー', max_length=20, verbose_name='ユーザー名')),
                ('house_common_fee', models.PositiveIntegerField(blank=True, default=500, null=True, verbose_name='共益費')),
                ('house_common_fee_date', models.PositiveIntegerField(blank=True, default=25, null=True, verbose_name='共益費の支払い期日')),
                ('housechore_title', models.CharField(default='割り当てられていません', max_length=100, verbose_name='家事')),
                ('housechore_desc', models.CharField(default='詳細なし', max_length=100, verbose_name='詳細')),
                ('done_weekly', models.BooleanField(blank=True, default=0, null=True, verbose_name='毎週の家事完了')),
                ('done_monthly', models.BooleanField(blank=True, default=0, null=True, verbose_name='公益費の支払い完了')),
                ('is_staff', models.BooleanField(default=False, verbose_name='ハウス管理者権限')),
                ('is_active', models.BooleanField(default=True, verbose_name='本登録完了')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='仮登録日')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.House')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
