# Generated by Django 2.2.13 on 2021-03-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='housechore_desc',
            field=models.CharField(default='no description', max_length=100),
        ),
    ]
