# Generated by Django 2.2.20 on 2021-04-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='common_fee',
            field=models.PositiveIntegerField(blank=True, default=500, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='common_fee_date',
            field=models.PositiveIntegerField(blank=True, default=25, null=True),
        ),
    ]
