# Generated by Django 3.0.14 on 2021-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=256, null=True, verbose_name='問い合わせ内容')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='日付')),
            ],
        ),
    ]
