# Generated by Django 2.2.20 on 2021-04-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210411_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='done_monthly',
            field=models.BooleanField(default=False, verbose_name='公益費の支払い完了'),
        ),
        migrations.AlterField(
            model_name='user',
            name='done_weekly',
            field=models.BooleanField(default=False, verbose_name='毎週の家事完了'),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_common_fee',
            field=models.PositiveIntegerField(blank=True, default=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_common_fee_date',
            field=models.PositiveIntegerField(blank=True, default=25, null=True),
        ),
    ]
