# Generated by Django 2.2.20 on 2021-04-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210411_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='common_fee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='共益費'),
        ),
        migrations.AlterField(
            model_name='house',
            name='common_fee_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='共益費の支払い期日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_common_fee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='共益費'),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_common_fee_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='共益費の支払い期日'),
        ),
    ]
