# Generated by Django 2.2.13 on 2021-03-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210321_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.House'),
        ),
    ]
