# Generated by Django 2.2.13 on 2021-03-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210321_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='housechore_desc',
            field=models.CharField(default='詳細なし', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='housechore_title',
            field=models.CharField(default='割り当てられていません', max_length=100),
        ),
    ]
