# Generated by Django 2.2.13 on 2021-03-20 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210320_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselecthouse',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.House'),
        ),
    ]
