# Generated by Django 2.2.13 on 2021-03-20 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210320_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSelectHouse',
            new_name='UserAndHouse',
        ),
    ]
