# Generated by Django 2.2.20 on 2021-04-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210411_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='common_fee',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='house',
            name='common_fee_date',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_common_fee',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_common_fee_date',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
