# Generated by Django 2.2.13 on 2021-03-21 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210321_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.House'),
        ),
    ]
