# Generated by Django 2.2.13 on 2021-03-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210320_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='userandhouse',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
