# Generated by Django 3.0.14 on 2021-05-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_requesthouseowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthouseowner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
    ]
