# Generated by Django 2.2.13 on 2021-03-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userandhouse_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='house',
            field=models.CharField(default='住んでいるハウス', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='ユーザー', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserAndHouse',
        ),
    ]
