# Generated by Django 3.0.14 on 2021-05-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210501_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesthouseowner',
            old_name='house',
            new_name='current_house',
        ),
        migrations.AddField(
            model_name='requesthouseowner',
            name='request_house',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='希望するハウス'),
        ),
    ]
