# Generated by Django 2.2.13 on 2021-03-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210320_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='house',
            field=models.CharField(default='not selected', max_length=20),
        ),
    ]
