# Generated by Django 2.2.20 on 2021-04-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210329_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='done_monthly',
            field=models.BooleanField(default=False, verbose_name='公益費の支払い完了'),
        ),
        migrations.AddField(
            model_name='user',
            name='done_weekly',
            field=models.BooleanField(default=False, verbose_name='毎週の家事完了'),
        ),
    ]
