# Generated by Django 2.2.20 on 2021-04-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210411_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='common_fee',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
