# Generated by Django 2.2.13 on 2021-03-20 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('users', '0008_auto_20210320_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='housechore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.HouseChore'),
        ),
    ]
