# Generated by Django 3.0.14 on 2021-05-18 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('users', '0008_auto_20210501_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquire',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session'),
        ),
    ]
