# Generated by Django 2.2.13 on 2021-03-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_housechore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='housechore',
            field=models.CharField(default='not assigned', max_length=100),
        ),
    ]
