# Generated by Django 2.2.20 on 2021-04-11 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_house_common_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='common_fee_date',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='user',
            name='house_common_fee_date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_common_fee_date', to='users.House'),
        ),
    ]
