# Generated by Django 2.2.13 on 2021-03-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210320_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='housechore',
            new_name='housechore_title',
        ),
        migrations.AddField(
            model_name='user',
            name='housechore_desc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
