FROM python:3.7.10
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
ADD . /code/

# "python manage.py makemessages -l en" のエラーを解消するため
RUN apt-get update && apt-get install -y gettext libgettextpo-dev
