version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  django:
    build:
      context: .
      dockerfile: Dockerfile.python
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    接続するサービス
    depends_on:
      - db

  # react:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.node
  #   command: npm start
  #   volumes:
  #     - .:/code
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env
  #   depends_on:
  #     - django

volumes:
  postgres_data:
