version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: DockerfilePython
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  # react:
  #   build:
  #     context: .
  #     dockerfile: DockerfileNode
  #   volumes:
  #     - .:/code
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - django

volumes:
  postgres_data:
