# Generated by Django 2.2.13 on 2021-03-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housechore',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
