# Generated by Django 3.0.14 on 2021-05-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_housechore_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='housechore',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効/無効'),
        ),
    ]
