# Generated by Django 2.2.13 on 2021-03-27 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210327_1557'),
        ('app', '0002_auto_20210321_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='housechore',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.House'),
        ),
    ]
