# Generated by Django 2.2.13 on 2021-03-28 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_housechore_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housechore',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.House'),
        ),
        migrations.AlterField(
            model_name='housechore',
            name='title',
            field=models.CharField(default='家事', max_length=100),
        ),
    ]
