# Generated by Django 2.2.13 on 2021-03-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210328_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housechore',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='housechore',
            name='title',
            field=models.CharField(default='家事', max_length=100, verbose_name='家事'),
        ),
    ]
